[server_configuration]
bind_address = "[::]:8080"
request_timeout = "10 seconds"
context = "/api/v1"
external_hosts = ["aaronr.digital", "www.aaronr.digital"]
connection = { max_lifetime = "5 minutes", graceful_shutdown_timeout = "15 seconds", tcp_nodelay = false }

[command_configuration]
max_concurrent_commands = 10
semaphore_acquire_timeout = "200 msec"
commands = [
    { id = "chronyc_sources", description = "chronyc sources", command = "/usr/bin/chronyc", args = [
        "-a",
        "-n",
        "sources",
        "-v",
    ] },
    { id = "chronyc_sourcestats", description = "chronyc sourcestats", command = "/usr/bin/chronyc", args = [
        "-a",
        "-n",
        "sourcestats",
        "-v",
    ] },
    { id = "df", description = "df", command = "/usr/bin/df", args = [
        "-h",
    ] },
    { id = "git_log", description = "git log", command = "/usr/bin/git", args = [
        "log",
        "-1",
    ] },
    { id = "ip_addr", internal_only = true, description = "ip addr", command = "/usr/sbin/ip", args = [
        "addr",
    ] },
    { id = "lscpu", description = "lscpu", command = "/usr/bin/lscpu" },
    { id = "lscpu_e", description = "lscpu -e", command = "/usr/bin/lscpu", args = [
        "-e",
    ] },
    { id = "netstat_an", internal_only = true, description = "netstat -an", command = "/usr/bin/netstat", args = [
        "-a",
        "-n",
    ] },
    { id = "sensors", description = "sensors", command = "/usr/bin/sensors" },
    { id = "top", description = "top", command = "/usr/bin/top", args = [
        "-b",
        "-n1",
    ] },
    { id = "top_ores", description = "top -o RES", command = "/usr/bin/top", args = [
        "-b",
        "-n1",
        "-o",
        "RES",
    ] },
    { id = "uptime", description = "uptime", command = "/usr/bin/uptime" },
    { id = "vmstat", description = "vmstat", command = "/usr/bin/vmstat" },
    { id = "w", internal_only = true, description = "w", command = "/usr/bin/w" },
]
