[server_configuration]
unix_socket_path = "./test"
request_timeout = "10seconds"
context = "/api/v1"

[command_configuration]
max_concurrent_commands = 1
semaphore_acquire_timeout = "200ms"
commands = [
    { id = "sleep", description = "sleep", command = "/bin/sleep", args = [
        "5",
    ] },
    { id = "vmstat", description = "vmstat", command = "/usr/bin/vmstat" },
    { id = "w", description = "w", command = "/usr/bin/w" },
]
