[server_configuration]
bind_address = "[::1]:8080"
request_timeout = "10 seconds"
context = "/api/v1"
connection = { max_lifetime = "5 minutes", graceful_shutdown_timeout = "15 seconds", tcp_nodelay = false }

[command_configuration]
max_concurrent_commands = 1
semaphore_acquire_timeout = "200 msec"
commands = [
    { id = "sleep", internal_only = true, description = "sleep", command = "/bin/sleep", args = [
        "5",
    ] },
    { id = "vmstat", description = "vmstat", command = "/usr/bin/vmstat" },
    { id = "w", description = "w", command = "/usr/bin/w" },
]
